export const action = {
	DOCUMENT_DELETED : 1,
	DOCUMENT_TITLE_SAVED : 2,
	BLOCK_TITLE_SAVED : 3,
	VERSION_TITLE_SAVED : 4,
	BLOCK_CREATED : 5,
	BLOCK_DELETED : 6,
	VERSION_CREATED : 7,
	VERSION_DELETED : 8,
	VERSION_SET_AS_PREFERRED : 9,
	CONTENT_SAVED : 10
}
